---
title: "Vignette_R2camtrapdp"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette_R2camtrapdp}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(R2camtrapdp)
```

## Create deployment

If you have deployment and observation data.

```{r}
data(Vdep)
data(Vobs)
```
Using Vdep, deployment (tibble data) was created as below,
```{r}
##create deployment
deployments<-create_deployments(
  deploymentID=Vdep$deploymentID,
  longitude=Vdep$longitude,
  latitude=Vdep$latitude,
  locationID=Vdep$locationID,
  deploymentStart_date=Vdep$startDate,
  deploymentStart_time=Vdep$startTime,
  deploymentEnd_date=Vdep$endDate,
  deploymentEnd_time=Vdep$endTime,
  cameraID=Vdep$cameraID,
  cameraModel=Vdep$cameraModel,
  cameraDelay=Vdep$Delay,
  cameraHeight=Vdep$Height,
  baitUse=Vdep$bait,
  setupBy=Vdep$setupBy)
```

## Create media
Using Vdep and Vobs, media (tibble data) was created as below,
```{r}
##settings
#media ID
mediaID<-paste(Vobs$institutionCode,
               Vobs$collectionCode,
               Vobs$locationID,
               as.numeric(factor(Vobs$filename)),
               sep="_")
#capture method
capturemethod<-"activityDetection"
nmedia<-length(mediaID)
captureMethod<-rep(capturemethod,nmedia)

#filePath
filePath<-paste("Video")

#fileName
fileName<-Vobs$filename
filetype<-tolower(unlist(lapply(strsplit(fileName,"\\."),"[",2)))

#filePublic
fileMediatype<-paste("video",filetype,sep="/")
filePublic<-!grepl("ヒト",fileName)

##create media
media<-create_media( mediaID=mediaID,
                     deploymentID=Vdep$deploymentID,
                     timestamp_date=Vobs$date,
                     timestamp_time=Vobs$time,
                     filePath=filePath,
                     filePublic=filePublic,
                     fileMediatype=fileMediatype,
                     captureMethod="activityDetection",
                     fileName=fileName)
```

## Create observation
Using Vobs, observation (tibble data) was created as below,
```{r}
#If the observations were media-based observations, observationLevel expressed as "media"
observationLevel<-"media"

#If the observations classified by human, classificationmethod expressed as "humam" 
classificationmethod<-"human"
#classificationprobability is the degree of certainty of the classification of the observed object (1=maximum certainty)
classificationprobability<-1

#create observationIDs that express the unique identifier of the observation 
observationID<-paste(mediaID,Vobs$pictID,sep="_")
#deploymentID is belong to deployment
deploymentID<-Vdep$deploymentID
#mediaID is belong to media
mediaID<-mediaID

#Timestamp (date and time) at which the observation started (e.g., the timestamp when the video or photo was taken)
tz="Japan"
timestamp<-paste(Vobs$date,Vobs$time)

#categorized observationType (animal, human, vehicle, blank, unknown, or unclassified)
observationType<-ifelse(Vobs$object=="hito","human",
                        ifelse(Vobs$object=="none","blank",
                               ifelse(Vobs$object=="unidentifiable","unknown","animal")))

#Scientific name of the animals observed
scientificName<-ifelse(is.na(Vobs$genus),Vobs$class,paste(Vobs$genus,Vobs$species))

#create observations
observations<-create_observations(observationID=observationID,
                                  deploymentID=deploymentID,
                                       mediaID=mediaID,
                                       eventStart=timestamp,
                                       eventEnd=timestamp,
                                       observationLevel=observationLevel,
                                       observationType=observationType,
                                       scientificName=scientificName,
                                       count=Vobs$individualCount,
                                       classificationMethod=classificationmethod,
                                       classificationProbability=classificationprobability
)

```

## Create datapackages
```{r}
#set taxsonomic information
taxonDB<-"itis"
t

```